22/12/24 (03:03:23) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
22/12/24 (03:03:23) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

22/12/24 (03:03:26) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
22/12/24 (03:03:26) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

24/12/24 (12:33:37) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
24/12/24 (13:12:19) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (09:48:07) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (10:50:29) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (10:51:27) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (14:17:42) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
26/12/24 (01:03:10) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
26/12/24 (03:30:27) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
26/12/24 (22:21:52) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
27/12/24 (00:06:21) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
27/12/24 (02:40:32) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
27/12/24 (05:11:42) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
27/12/24 (14:28:23) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
27/12/24 (14:54:41) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
29/12/24 (02:16:44) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
29/12/24 (05:12:54) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
31/12/24 (05:37:00) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
31/12/24 (14:14:48) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
03/01/25 (04:59:34) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
03/01/25 (08:02:13) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
03/01/25 (19:01:43) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
03/01/25 (19:01:53) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
03/01/25 (19:18:45) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
06/01/25 (19:32:12) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
11/01/25 (15:13:46) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
11/01/25 (15:13:46) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
    ~~~~~~~~~~~~~~~^^
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
11/01/25 (15:13:46) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

11/01/25 (15:13:53) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
11/01/25 (18:40:25) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
11/01/25 (18:40:25) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
    ~~~~~~~~~~~~~~~^^
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
11/01/25 (18:40:25) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

11/01/25 (18:40:41) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
11/01/25 (18:40:42) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
    ~~~~~~~~~~~~~~~^^
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
    ~~~~~~~~~~~~~~~~^^
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
11/01/25 (18:40:42) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

14/01/25 (05:34:41) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (09:07:28) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (09:32:29) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (09:33:02) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (09:33:08) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (09:42:53) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (12:52:10) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (12:57:24) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
14/01/25 (12:59:24) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
15/01/25 (22:34:24) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
16/01/25 (01:30:21) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
16/01/25 (14:38:27) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
01/02/25 (02:35:07) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
01/02/25 (02:35:33) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
01/02/25 (02:36:03) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
