22/12/24 (03:03:23) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
22/12/24 (03:03:23) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

22/12/24 (03:03:26) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2959, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3991, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2739, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Sign not allowed in string format specifier
22/12/24 (03:03:26) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

24/12/24 (12:33:37) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
24/12/24 (13:12:19) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (09:48:07) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (10:50:29) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (10:51:27) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
25/12/24 (14:17:42) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
26/12/24 (01:03:10) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
26/12/24 (03:30:27) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
26/12/24 (22:21:52) | ERROR: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/kirk/.config/bpytop/themes'
